name = "prisma-d1-example"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
[observability]
enabled = true

[build]
command = "npm run db:generate && npm run build"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "flavi-crm-next"
database_id = "bdc3405b-6cf3-450b-9030-11c263c02cde"