name = "prisma-d1-example"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
[observability]
enabled = true

[build]
command = "npm run db:generate && npm run build"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "crm-1"
database_id = "e400ca26-1e7f-48c7-add0-4cedd12ce4fc"